name: flutter_audio_query_example
description: Demonstrates how to use the flutter_audio_query plugin.
author: Marcos Antonio Boaventura <scavenger.gnu@gmail.com>

environment:
  sdk: ">=2.1.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  flutter_audio_query:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any


flutter:

  uses-material-design: true

  assets:
    - assets/no_cover.png